# Generated by Django 5.2 on 2025-04-29 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_telechargement', models.IntegerField()),
                ('nb_Etudiant', models.IntegerField()),
                ('nb_Sujet_disponible', models.IntegerField()),
                ('taux_adoption', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField()),
                ('description', models.TextField(blank=True)),
                ('matiere', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('annee', models.CharField(max_length=60)),
                ('auteur', models.CharField(max_length=60)),
                ('Sujet_url', models.FileField(upload_to='sujets/')),
                ('Corriger_url', models.FileField(upload_to='corriges/')),
                ('date_upload', models.DateTimeField(auto_now=True)),
                ('nb_telechargement', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suspendre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateSuspension', models.DateTimeField()),
                ('Motif', models.TextField(blank=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldtopic.admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldtopic.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Telecharger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTelechargement', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldtopic.etudiant')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldtopic.sujet')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('etudiant', 'Etudiant'), ('superadmin', 'SuperAdmin')], max_length=20)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('etat', models.CharField(default='inactif', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visualiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visualisation', models.DateTimeField(auto_now=True)),
                ('type_statistique', models.CharField(max_length=60)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldtopic.admin')),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldtopic.stats')),
            ],
        ),
    ]
