# Generated by Django 5.2 on 2025-05-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldtopic', '0002_newletter_newslettermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='preenregistrementmatricule',
            name='Filiere',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preenregistrementmatricule',
            name='Niveau',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='preenregistrementmatricule',
            name='nom',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='preenregistrementmatricule',
            name='prenom',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
