# Generated by Django 5.2 on 2025-04-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldtopic', '0002_user_alter_etudiant_matricule_alter_admin_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreEnregistrementMatricule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
