# Generated by Django 5.2 on 2025-05-04 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldtopic', '0003_preenregistrementmatricule_filiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='permissions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='role',
            field=models.CharField(default='SuperAdmin', max_length=30),
        ),
    ]
