# Generated by Django 5.2 on 2025-04-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oldtopic', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
