# Generated by Django 5.2 on 2025-05-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldtopic', '0004_superadmin_date_creation_superadmin_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
