# Generated by Django 5.2 on 2025-05-06 12:34

import oldtopic.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldtopic', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='Corriger_url',
            field=models.FileField(upload_to=oldtopic.utils.corriger_upload_path),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='Sujet_url',
            field=models.FileField(upload_to=oldtopic.utils.sujet_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=oldtopic.utils.photo_upload_path),
        ),
    ]
