# Generated by Django 5.2 on 2025-05-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldtopic', '0007_alter_sujet_corriger_url_alter_sujet_sujet_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='filiere',
            field=models.CharField(choices=[('IGL', 'IGL'), ('RIT', 'RIT'), ('DROIT', 'DROIT'), ('FBA', 'FBA'), ('SEG', 'SEG'), ('PFC', 'PFC'), ('ACG', 'ACG')], default='IGL', max_length=60),
        ),
        migrations.AddField(
            model_name='sujet',
            name='niveau',
            field=models.CharField(choices=[('licence_1', 'Licence 1'), ('licence_2', 'Licence 2'), ('licence_3', 'Licence 3'), ('BTS_1', 'BTS 1'), ('BTS_2', 'BTS 2'), ('master_1', 'Master 1'), ('master_2', 'Master 2')], default='licence_1', max_length=60),
        ),
        migrations.AlterField(
            model_name='preenregistrementmatricule',
            name='Filiere',
            field=models.CharField(choices=[('IGL', 'IGL'), ('RIT', 'RIT'), ('DROIT', 'DROIT'), ('FBA', 'FBA'), ('SEG', 'SEG'), ('PFC', 'PFC'), ('ACG', 'ACG')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preenregistrementmatricule',
            name='Niveau',
            field=models.CharField(choices=[('licence_1', 'Licence 1'), ('licence_2', 'Licence 2'), ('licence_3', 'Licence 3'), ('BTS_1', 'BTS 1'), ('BTS_2', 'BTS 2'), ('master_1', 'Master 1'), ('master_2', 'Master 2')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='type',
            field=models.CharField(choices=[('Examen', 'Examen'), ('TD', 'Traveaux Dirigés'), ('TP', 'Traveaux Pratiques'), ('Devoir', 'Devoir'), ('Interrogation', 'Interrogation')], max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=130),
        ),
    ]
