# Generated by Django 5.2 on 2025-05-20 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldtopic', '0008_sujet_filiere_sujet_niveau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newletter',
            name='date_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='newletter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
